# Generated by Django 4.2.6 on 2023-11-03 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookstore", "0002_alter_book_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="price",
            field=models.DecimalField(
                blank=True, db_index=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
